version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: ticketing_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TicketingSystem
    ports:
      - "3306:3306"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
