version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: ticketing_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TicketingSystem
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
volumes:
  mysql_data: